spring:
  datasource:
    url: ${DATABASE_URL_PROD}
    username: ${DATABASE_USERNAME_PROD}
    password: ${DATABASE_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true